-- CARİ HESAPLAR TOPLU AKTARIM SQL (ERP -> WEB)
-- Toplam Kayıt: 462
-- Oluşturma Tarihi: 12.01.2026 13:52:38

INSERT INTO cari_hesaplar (
    cari_kodu, cari_adi, telefon, eposta, vergi_dairesi, vergi_no, cari_tipi, kaynak, guncelleme_tarihi
) VALUES 
('07RÜZGAR', '07 RÜZGAR MARKET - HARUN TOLAY', '05416848386', '', 'MANAVGAT', '40474894910', 'Müşteri', 'erp', NOW()),
('ABİDİN', 'AVA MARKET - ABİDİN TEKİN', '', '', 'KEMER V.D', '37180219786', 'Müşteri', 'erp', NOW()),
('ACİL', 'ACİL BÜFE - SİNAN PINAROĞLU', '', '', 'ÜÇKAPILAR', '21041598202', 'Müşteri', 'erp', NOW()),
('ADALYA', 'ADALYA DENİZ MALZEMELERİ OYUNCAK KOZ GIDA TURZ İTH İHR SAN TİC LTD ŞTİ', '', '', 'KURUMLAR', '0070587143', 'Tedarikçi', 'erp', NOW()),
('ADRASAN HEDİYELİK', 'ADRASAN HEDİYELİK', '', '', 'KUMLUCA', '18355421548', 'Müşteri', 'erp', NOW()),
('AHMET ER', 'AHMET ER', '', '', 'MANAVGAT', '10231716540', 'Müşteri', 'erp', NOW()),
('AKIN', 'AKIN TÜRKEKUL', '', '', '', '', 'Müşteri', 'erp', NOW()),
('AKSU ÇAMLIK', 'AKSU ÇAMLIK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ALİS', 'ALİS MARKET - İLYAS KAYA', '', '', 'KALEKAPI', '65506242392', 'Müşteri', 'erp', NOW()),
('AMCAM', 'AMCAM MARKET - İBRAHİM ÖZCAN', '', '', 'SERİK', '30179089018', 'Müşteri', 'erp', NOW()),
('ANDİFLİ', 'ANDİFLİ MARKET', '', 'defaultpk@andiflimarket.com.tr', 'KAŞ', '23956225396', 'Müşteri', 'erp', NOW()),
('ANTALYA KIRTASİYE', 'ANTALYA KIRTASİYE OFİS & BÜRU MALZEMELERİ - HAKAN', '', '', 'DÜDEN', '21265299466', 'Müşteri', 'erp', NOW()),
('ANTEVENT', 'ANT EVENT ALİ BEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ANTİK MARKET', 'ANTİK MARKET - HALİSE GÜRBÜZ', '', '', 'SERİK V.D', '158 293 451 64', 'Müşteri', 'erp', NOW()),
('ARAS', 'ARAS KARGO ALTINOVA ŞUBESİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ARIA', 'ARIA EVENT ORGANİZASYON', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ARMAĞAN', 'ARMAĞAN KIRTASİYE - ARMAĞAN PALAMUTÇU', '', '', 'KUMLUCA', '16621469836', 'Müşteri', 'erp', NOW()),
('ASPENDOS', 'ASPENDOS SOUVENİR - AHMET ÜNAL', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ASYA', 'ASYA OYUNCAK İTHALAT İHR SAN VE TİC LTD', '', '', 'GÜNEŞLİ', '0911063280', 'Tedarikçi', 'erp', NOW()),
('AVCIOGLU', 'AVCIOĞLU MARKET - METE AVCI', '', '', 'SERİK', '211 903 48 390', 'Müşteri', 'erp', NOW()),
('AYDEMİR', 'AYDEMİR TOYS - MAS DENİZ MALZEMELERİ PLASTİK İMALAT SAN İTH İHR LTD ŞTİ', '', '', 'MANAVGAT', '6121799531', 'Tedarikçi', 'erp', NOW()),
('AYHAN ERMEÇ', 'AYHAN ERMEÇ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BAHADIR', 'BAHADIR SÜREK - KADRİYE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BAHADIR2', 'BAHADIR ÇAMYUVA', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BAHADIR3', 'BAHADIR SÜREK - BELEK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BAHADIR4', 'BAHADIR SÜREK - KADRİYE MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BAYRAK', 'Z__XML BAYİ - MAVİ TEXTİL - FURKANEMİN BAYRAK', '', '', 'TEPECİK', '11056316700', 'Müşteri', 'erp', NOW()),
('BELEK BEACH OTEL', 'SVİTLANA ROLHİNA BAHAR SVİTLANA ROLHİNA BAHAR', '', '', 'SERİK', '52585128938', 'Müşteri', 'erp', NOW()),
('ZAKKUM-BEREKET', 'ZAKKUM - BEREKET MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BEST MARKET', 'BEST MARKET MUSTAFA YILDIZ', '', '', 'SERİK', '22459305000', 'Müşteri', 'erp', NOW()),
('BİKİNİ', 'BİKİNİ WORLD - RECEP ŞAFAK', '', '', 'KALEKAPI', '20953458758', 'Müşteri', 'erp', NOW()),
('BİM', 'BİM MARKETLER', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BİRLİK', 'BİRLİK OYUNCAK SAN V E TİC LTD ŞTİ', '', '', 'GÜNEŞLİ', '1780029122', 'Tedarikçi', 'erp', NOW()),
('BİSART', 'ELA QUALITY - İNCİ GİRİŞ', '', '', 'SERİK', '51340457672', 'Müşteri', 'erp', NOW()),
('BİZİM OYUNCAK', 'BİZİM OYUNCAK  - DOĞU BEYAZIT NEVZAT', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('BLUE FİSH', 'BLUE FİSH OTEL - ALANYA - HASAN SİDAR', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BONCUK', 'BONCUK MARKET - NECİP BONCUK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BULVAR', 'İPEK GIDA İNŞ. TİC. LTD. ŞTİ MERKEZ', '', '', 'FİNİKE', '4790113952', 'Müşteri', 'erp', NOW()),
('BULVAR 3', 'İPEK GIDA İNŞAAT TİC LTD ŞTİ ŞUBE:3', '', '', 'FİNİKE', '4790113952', 'Müşteri', 'erp', NOW()),
('BY ALDİ', 'BAY - ALDİ MARKET MEHMET UZUN', '', '', 'SERİK', '28570747392', 'Müşteri', 'erp', NOW()),
('BYR', 'XML - BYR POS BİLİŞİM UĞUR YILDIZ', '', '', 'DÜDEN', '15901486778', 'Müşteri', 'erp', NOW()),
('CANCAN', 'CANCAN MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('CANEM', 'CANEM OYUNCAK SAN VE DIŞ TİC LTD ŞTİ', '', '', 'GÜNEŞLİ', '1980315685', 'Tedarikçi', 'erp', NOW()),
('CARELTA', 'CARELTA OTEL - MURAT', '', '', '', '', 'Müşteri', 'erp', NOW()),
('CASPER', 'UYAROĞLU SPOR MALZ TEKS GIDA İNŞ VE OTOM SAN TİC LTD ŞTİ', '', '', 'GÜNEŞLİ', '8980585851', 'Müşteri', 'erp', NOW()),
('CEMRE', 'CEMRE MARKET - ZAHİDE GÖRMEZ', '', '', 'KEMER', '20788150674', 'Müşteri', 'erp', NOW()),
('CEO', 'CEO AMBALAJ PLASTİK ISI YALITIM PAZ SAN TİC LTD ŞT', '', '', 'KEMALPAŞA', '3250075160', 'Müşteri', 'erp', NOW()),
('CEREN', 'CEREN KAĞIT VE KIRTASİYE SAN A.Ş', '', '', '6330050957', 'MARMARA KURUMLA', 'Müşteri', 'erp', NOW()),
('CEREN HEDİYELİK', 'CEREN HEDİYELİK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('CEYLAN', 'CEYLAN TEKSTİL - GAZELLE OTELCİLİK TURİZM SAN TİC LTD ŞTİ', '', '', 'KURUMLAR', '3891431179', 'Müşteri', 'erp', NOW()),
('CHAS', 'XML-CHASHOBBY STORE - CİHANGİR ÖZ', '', '', 'BİTLİS', '48679514206', 'Müşteri', 'erp', NOW()),
('CRİSTAL', 'CRİSTAL WATER WORLD - MUSTAFA KEMAL KARABOĞA', '', '', '', '', 'Müşteri', 'erp', NOW()),
('CRİSTAL FAMİLY', 'CRİSTAL FAMİLY - IC 7 TURİZM GIDA LTD. ŞTİ.', '', '', 'KURUMLAR', '4651518219', 'Müşteri', 'erp', NOW()),
('CRİSTAL2', 'SELECTUM LUXURY - CRİSTAL WATERWORLD 2', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ÇERKEZ MARKET', 'ÇERKEZ MARKET', '', '', 'KALEKAPI', '58450427892', 'Müşteri', 'erp', NOW()),
('ÇINAR', 'ÇINAR OYUNCAK - TUĞBA BAŞCI', '', '', 'ÜÇKAPILAR', '3890463369', 'Tedarikçi', 'erp', NOW()),
('ÇS', 'ÇİÇEK SEPETİ - GÜRBÜZ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ÇS-WORLD', 'ÇİÇEK SEPETİ - WORLD TOYS', '', '', '', '', 'Müşteri', 'erp', NOW()),
('D', 'DÜZELTME CARİSİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('DAĞ', 'DAG HEDİYELİK ESYA - MUSLUM DAG', '', '', 'KALEKAPISI', '57433499352', 'Müşteri', 'erp', NOW()),
('DAĞ2', 'ÖZAYDAĞ HEDİYELİK GIDA VE TEKS. PAZ. İTH. İHR. TİC LTD. ŞTİ.', '', '', 'KURUMLAR', '6640727623', 'Müşteri', 'erp', NOW()),
('DEDE', 'FEN OYUNCAK VE MUTFAK EŞYALARI PAZ TIC LTD ŞTİ', '', '', 'GÜNEŞLİ', '3850113095', 'Tedarikçi', 'erp', NOW()),
('DEKOR', 'DEKOR BALON OYUNCAK VE KIRTASİYE HIRDAVAT YALÇIN DEMİRTAŞ', '', '', 'HOCAPAŞA', '42133477618', 'Tedarikçi', 'erp', NOW()),
('DELFİN1', 'DELFİN HEDİYELİK - OSMAN AKBULUT', '', '', 'SERİK', '16987487796', 'Müşteri', 'erp', NOW()),
('DENİZ ŞAHİN', 'DENİZ ŞAHİN ŞAHİNOĞULLARI YAPI KIRTASİYE', '', '', 'KEMER', '7910458080', 'Müşteri', 'erp', NOW()),
('DENİZ TOP', 'DENİZ TOP SPORT - KADİR DENİZ', '', '', 'TOPÇUMEYDANI', '14207955070', 'Müşteri', 'erp', NOW()),
('DORUK', 'DORUK TREND - EŞREF GÖK', '', '', 'MEVLANA', '43999616074', 'Müşteri', 'erp', NOW()),
('DUAŞ', 'DENİZ MARKET - DUAŞ GIDA', '', '', '', '', 'Müşteri', 'erp', NOW()),
('DURAN', 'DURAN BAKKAL - BİCAN DURAN', '', '', 'KUMLUCA', '17680444048', 'Müşteri', 'erp', NOW()),
('DURU', 'DURU İTR.DEPOSU SAN. VE TİC. A.Ş.', '', '', 'ANTALYA KURUMLAR', '3190024890', 'Tedarikçi', 'erp', NOW()),
('E MARKET', 'YAZ GIDA TİCARET ANONİM ŞİRKETİ', '', '', 'KURUMLAR', '9431171872', 'Müşteri', 'erp', NOW()),
('EKİCİ TURİZM', 'EKİCİ TURİZM LTD ŞTİ', '', '', 'KURUMLAR', '3280021936', 'Müşteri', 'erp', NOW()),
('EKİZ MARKET', 'BAYRAM EKİZ', '', '', 'SERİK', '26773162318', 'Müşteri', 'erp', NOW()),
('ELİFHAN', 'ELİFHAN GIDA TURİZM TİC. A.Ş.', '', '', 'MANAVGAT', '3320445085', 'Müşteri', 'erp', NOW()),
('EMEL', 'EMEL MARKET - HALİS KARSLI', '', '', 'ÜÇKAPILAR', '16262043396', 'Müşteri', 'erp', NOW()),
('ENFAL', 'ENFAL OYUNCAK - KANZ', '', '', 'GÜNEŞLİ', '3350688460', 'Tedarikçi', 'erp', NOW()),
('ERDEM', 'ERDEM OYUNCAK', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('ROBİNSON', 'ROBİNSON CLUB NOBİLİS OTEL MARKETİ', '', '', 'SERİK', '44719612666', 'Müşteri', 'erp', NOW()),
('ERKOL', 'ERKOL OYUNCAK SAN VE TIC LTD ŞTİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('EROL ŞAHAN', 'EROL ŞAHAN', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ETHEM', 'ETHEM OYUNCAK - İBRAHİM HALİL BAYGELDİ', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('EUROSHOP', 'EUROSHOP TEKSTİL DERİ TURİZM SAN LTD ŞTİ MEHMET YİĞİT', '', '', 'SERİK', '381 071 24 11', 'Müşteri', 'erp', NOW()),
('FALEZ', 'FALEZ MARKET - MESUT MEMİŞ', '', '', 'FİNİKE MAL MÜD', '177288 74486', 'Müşteri', 'erp', NOW()),
('FARUK GÜR - HAKKARİ', 'FARUK GÜR - HAKKARİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('FATİH', 'FATİH ER - BOĞAZKENT', '', '', 'SERİK', '17080484620', 'Müşteri', 'erp', NOW()),
('FATİH ÖZCAN', 'FATİH ÖZCAN - GÜNDOĞDU SEVGİ HEDİYELİKTEN KAÇAK', '', '', 'ÜÇKAPILAR', '179 848 94 662', 'Müşteri', 'erp', NOW()),
('FERHAT', 'FERHAT OYUNCAK TOPTAN - PERAKENDE OYUNCAK SATIŞI', '', '', 'MANAVGAT', '376 427 637 72', 'Tedarikçi', 'erp', NOW()),
('FİYONK', 'FYONG İÇ GİYİM - MUZAFFER KÜLAHÇILAR', '', '', 'ÜÇKAPILAR', '6050126931', 'Müşteri', 'erp', NOW()),
('GEPETTOYS', 'GEPETTOYS OYUNCAK SAN VE TİC LTD ŞTİ', '', '', 'GÜNEŞLİ', '3940486285', 'Tedarikçi', 'erp', NOW()),
('GG', 'GİTTİ GİDİYOR - SATIŞI', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GG-WORLD', 'GİTTİGİDİYOR - WORLD TOYS', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GÖKÇE', 'GÖKÇE OYUNCAK - FİLİZ KOŞ BEBEK GEREÇLERİ', '', '', 'MANAVGAT', '24680274834', 'Müşteri', 'erp', NOW()),
('GÖKER', 'GÖKER KASIMOĞLU', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GÖYNÜK', 'GÖYNÜK KIRTASİYE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GRANDHABER', 'GRAND HABER - KEMER ŞİRİNLER MURAT ABİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GRANDPARK', 'GRANDPARK - EMRAH KARA', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GREEN', 'GREEN STAR MARKET - YONÜS ÇALIŞKAN', '', '', 'KEMER', '34093700646', 'Müşteri', 'erp', NOW()),
('GÜL HEDİYELİK', 'GÜL HEDİYELİK - HÜSEYİN ÖZDEMİR', '', '', 'SERİK', '36821042400', 'Müşteri', 'erp', NOW()),
('GÜNEŞ', 'GÜNEŞ TEKSTİL - ALİ GÜNEŞ', '', '', 'Kalekapı', '20048770604', 'Müşteri', 'erp', NOW()),
('GÜNEŞCAN', 'ÖMER GÜNEŞ - GÜNEŞCAN BUTİK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GÜNYAPI', 'GÜNYAPI MARKET İZO.HIR.TUR.GUZ.MRK.KUY.İNŞ.MLZ.MİM MÜH.MOB.ORB.ÜRN.VE PLS.İTH.İHR.SAN.VETİC.LTD.STİ.', '', '', 'KURUMLAR', '4380387297', 'Müşteri', 'erp', NOW()),
('GÜRBÜZ', 'GÜRBÜZ OYUNCAK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GÜRBÜZWEB', 'WWW.GÜRBÜZOYUNCAK.COM', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GÜRKAN', 'GÜRKAN GIDA VE İTH. MAD SAN VE TİC LTD ŞTİ', '', '', 'GÜNEŞLİ V.D.', '445 001 57 09', 'Müşteri', 'erp', NOW()),
('HAMİT', 'HAMİT TAHA KALKAN', '', '', 'VERGİ DENETMENLİĞİ BİRİMİ', '48973741902', 'Müşteri', 'erp', NOW()),
('HARUN AKYOL', 'AKYOL SPOR GİYİM', '', '', '', '', 'Müşteri', 'erp', NOW()),
('HASDEN', 'HAS-DEN GIDA TURİZM TEKS TAŞ İNŞ İLETİŞİM TELEKOM HİZM SAN TİC LTD ŞTİ', '', '', 'ANTALYA KURUMLAR', '4580485815', 'Müşteri', 'erp', NOW()),
('HB', 'HEPSİBURADA - SATIŞI', '', '', '', '', 'Müşteri', 'erp', NOW()),
('HB-WORLD', 'HEPSİBURADA SATIŞI - WORLD TOYS', '', '', '', '', 'Müşteri', 'erp', NOW()),
('HIZLI', 'HIZLIVEUCUZ - UĞUR ÇOBAN', '', '', '', '', 'Müşteri', 'erp', NOW()),
('İDEFİX', 'İDEFİX - GÜRBÜZ OYUNCAK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('İDRİS', 'İPEKYOLU HEDİYELİK TOPTAN HEDİYELİK BİJÜTERİ TEKSTİL - MEHMET İDRİS ZÜLFÜKAR', '', '', 'DÜDEN', '18655312270', 'Müşteri', 'erp', NOW()),
('İKİZLER', 'İKİZLER MARKET', '', '', 'KALEKAPI', '43966292720', 'Müşteri', 'erp', NOW()),
('İSMAİL HANTAL', 'İSMAİL HANTAL - RİZE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('İSMET', 'İSMET KONAK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('İSTANBUL OUTLET2', 'İSTANBUL OUTLET ÖRNEKKÖY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('İSTANBUL TEXTİL', 'İSTANBUL TEXTİL - SERKAN KÜÇÜK', '', '', 'KEMER', '16270308806', 'Müşteri', 'erp', NOW()),
('JASMİN', 'JASMİN BEBE - İREM SUBAŞI', '', '', 'KALEKAPI', '28136633350', 'Müşteri', 'erp', NOW()),
('JOY EVENT', 'JOY EVENT - MEHMET BEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('JUMBO', 'JUMBO OYUNCAK - SELÇUK ÖZDEMİR', '', '', 'DÜDEN', '65443128520', 'Müşteri', 'erp', NOW()),
('JUMBO2', 'HASAN ÖZDEMİR - JUMBO', '', '', '', '', 'Müşteri', 'erp', NOW()),
('JUMBO3', 'HASAN ÖZDEMİR JUMBO - MAKARNA', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KALENDER', 'KALENDER SERA GIDA ÜRETİM LTD. ŞTİ.', '', '', 'KURUMLAR', '4920549978', 'Müşteri', 'erp', NOW()),
('KALKAN KIRTASİYE', 'KALKAN KIRTASİYE - VEDAT YAZICI', '', '', 'KAŞ', '27998260148', 'Müşteri', 'erp', NOW()),
('KAPLAN KIRTASİYE', 'KAPLAN KIRTASİYE - AYBÜKE UĞUZ KAPLAN', '', '', 'BUCAK', '10012930882', 'Müşteri', 'erp', NOW()),
('KARA', 'KARA TOYS OYUNCAK DÜNYASI KEMAL KARA', '', '', 'DÜDEN', '17965400912', 'Tedarikçi', 'erp', NOW()),
('KARACAN', 'ELİZ MARKET - ALİ ORMANCI', '', '', 'KUMLUCA', '11350655062', 'Müşteri', 'erp', NOW()),
('KARİZMA', 'KARİZMA MARKET - TAHSİN UÇUCU', '', '', 'KEMER V.D', '21049509606', 'Müşteri', 'erp', NOW()),
('KARTOY', 'KARTOY OYUNCAK SAN VE TİC LTD ŞTİ', '', '', 'GÜNEŞLİ', '5261337288', 'Tedarikçi', 'erp', NOW()),
('KAYA MARKET', 'KAYA MARKET - GÖKHAN KAYA', '05072573626', '', 'SERİK V.D', '19405407000', 'Müşteri', 'erp', NOW()),
('KEMAL DAĞ', 'KEMAL DAĞ - GÖYNÜK', '', '', 'KEMER', '2650588509', 'Müşteri', 'erp', NOW()),
('KEMBAY', 'KEMBAY OYUNCAK', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('KEPEZ EKMEK BÜFESİ', 'KEPEZ EKMEK BÜFESİ - MURAT SİVRİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KERVAN', 'XML - KERVANSANAL WEB EGITIM DANISMA TİC. SAN LTD. ŞTİ', '', '', 'DIKIMEVI', '5451269653', 'Müşteri', 'erp', NOW()),
('KETSAN', 'KETSAN OYUNCAK', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('KETTE', 'KETTE PLASTIK - HÜSEYİN KETTE', '', '', 'BAYRAMPASA', '444 040 513 50', 'Tedarikçi', 'erp', NOW()),
('KETTE-ZÜLKÜF', 'KETTE ZÜLKÜF ŞAHİN', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KIZIL', 'OSMAN KIZILKAYA VARİSLERİ ADİ ORTAKLIĞI', '', '', 'KEMERALTI', '5600581634', 'Tedarikçi', 'erp', NOW()),
('KIZILZAYİ', 'KIZILKAYA ZAYİ ÜRÜNLER', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KK', 'KREDİ KARTI SATIŞLAR', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KLADOS', 'KLADOS OTEL - SELAMİ BEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KOÇ', 'KOÇ BÜFE - RAZİYE BALIK', '', '', 'SERİK V.D', '288310 750 04', 'Müşteri', 'erp', NOW()),
('KOÇAK', 'KOÇAK HEDİYELİK - MEHMET EMİN KOÇAK', '', '', 'SERİK', '13030620162', 'Müşteri', 'erp', NOW()),
('KOÇAK-2', 'KOÇAK HEDİYELİK 2 - MEHMET EMİN KOÇAK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KÖŞEM', 'KÖŞEM MARKET - ALANYA MUSTAFA DURGUT', '', '', 'ALANYA', '2437168190', 'Müşteri', 'erp', NOW()),
('KUBİLAY', 'KUBİLAY ÇITAK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KURT', 'ALİÇO MARKET - ALİCAN EKŞİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KUŞADASI İSA', 'KUŞADASI - İSA BEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('LABOR', 'LABOR BİLİŞİM MEDİKAL İNŞAAT YAYINCILIK TİC.LTD.ŞTİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('LAKEYİF', 'LA KEYİF ESENGÜL KORKMAZ', '', '', 'ÜÇKAPILAR', '45433175024', 'Müşteri', 'erp', NOW()),
('LEVENT', 'LEVENT ŞİMŞEKOĞLU', '', '', 'KUMLUCA', '22990763086', 'Müşteri', 'erp', NOW()),
('LEVENT GELGEÇ', 'LEVENT GELGEÇ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('LİDYA MARKET', 'LİDYA MARKET - İBRAHİM DOĞRUBAKAN', '', '', 'SERİK', '23809260000', 'Müşteri', 'erp', NOW()),
('LİMAK', 'LİMAK LARA - CEM', '', '', '', '', 'Müşteri', 'erp', NOW()),
('LİSİNYA', 'XML BAYİ LİSİNYA - ELVAN ÇAGLAR BODRUMLU', '', '', '10151059024', 'ÜÇKAPILAR', 'Müşteri', 'erp', NOW()),
('LOLY', 'LOLYPOP OYUN EVİ DEMRE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('M.HANTAL', 'HANTALOĞLU KARA VE DENİZ MALZEMELERİ', '', '', 'İYİ DERE MAL. MUD', '4570483464', 'Müşteri', 'erp', NOW()),
('MALİMOĞLU', 'MALİMOĞLU KUY. TUR. DERİ TEKS. LTD. ŞTİ.', '', '', 'MANAVGAT', '6110353756', 'Müşteri', 'erp', NOW()),
('MARDAN', 'MARDAN OTEL MARKETİ - EMRE ŞEKER', '', '', '', '', 'Müşteri', 'erp', NOW()),
('MAY', 'MAY HOTEL MARKETİ - SÜLEYMAN BEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('MAYA', 'MAYA WORLD OTEL - SELAMİ BEY', '', '', 'MANAVGAT', '434 299 866 78', 'Müşteri', 'erp', NOW()),
('MAZLUM', 'MAZLUM HEDİYELİK - FERHAT ERDEMCİ', '', 'seyiterdemci@icloud.com', 'KEMER', '55549577186', 'Müşteri', 'erp', NOW()),
('MEHMET FATİH', 'MEHMET FATİH YILMAZ', '', '', 'KALEKAPI', '46822185310', 'Müşteri', 'erp', NOW()),
('MENTEŞ', 'MENTEŞBEY OTOBÜS İKRAM MEHMET NURETTİN PARLAR', '', '', 'ÜÇKAPILAR', '23938202346', 'Müşteri', 'erp', NOW()),
('MİÇO', 'MİÇO MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('MİLANO', 'MİLANO BUTİK - SÜLEYMAN KÜÇÜK - KUNDU', '', '', 'KALEKAPI', '28006107936', 'Müşteri', 'erp', NOW()),
('MİRA', 'MİRA TEKSTİL', '', '', 'KALEKAPI', '15694065624', 'Müşteri', 'erp', NOW()),
('MOOD', 'MOOD OYUN OYUNCAK SAN TİC LTD ŞTİ', '', '', 'ANTALYA KURUMLAR', '6221684546', 'Müşteri', 'erp', NOW()),
('MUAMMER GÜRKAN', 'MUAMMER GÜRKAN - GRAND BAZAAR', '', '', 'KALEKAPI', '20005350320', 'Müşteri', 'erp', NOW()),
('MUEM BEBE', 'MUEM CHİLD WEAR  - MÜKERREM ÇALIŞKAN', '', '', 'KALEKAPI', '34075701210', 'Müşteri', 'erp', NOW()),
('MURAT DOĞAN', 'MURAT DOĞAN - BEACH MARKET SALİH BAYĞIN', '', '', '', '', 'Müşteri', 'erp', NOW()),
('MUSTAFA SILAMOR', 'MUSTAFA SILAMOR MUSTAFA SILAMOR', '', '', 'KALEKAPI', '19190785864', 'Müşteri', 'erp', NOW()),
('N11', 'N11 - SATIŞI', '', '', '', '', 'Müşteri', 'erp', NOW()),
('N11WORLD', 'N11 - WORLDTOYS', '', '', '', '', 'Müşteri', 'erp', NOW()),
('NAFİ', 'İSTANBUL TEKSTİL - NAFİ DUYUM', '', '', '', '', 'Müşteri', 'erp', NOW()),
('NATUR', 'WOODLİNE - NA.TUR TURİZM TEKS. İNŞ. TİC. LTD ŞTİ', '', '', 'KEMER', '6270085450', 'Müşteri', 'erp', NOW()),
('NURİYE SEVİNÇ', 'NURİYE SEVİNÇ - NEVŞEHİR - ADA KIR BAHÇESİ', '', '', 'AVANOS', '13718792198', 'Müşteri', 'erp', NOW()),
('OKÇU AV ELAZIĞ', 'BİRKAN OKÇU - OKÇU AV MARKET ELAZIĞ', '', '', 'KARAKOÇAN', '36934282120', 'Müşteri', 'erp', NOW()),
('ONYIL', 'ONYIL HEDIYELIK EŞYA SAN. VE TIC. LTD ŞTİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('OPTİMUM', 'OPTİMUM SPOR', '', '', '', '', 'Müşteri', 'erp', NOW()),
('OPUS', 'OPUS KUY SEY TUR TİC LTD ŞTİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ORMANCI', 'ORMANCI BÜFE - ADRASAN', '', '', '', '', 'Müşteri', 'erp', NOW()),
('OSMAN GEZER', 'OSMAN GEZER', '', '', '', '', 'Müşteri', 'erp', NOW()),
('OUTLET KUNDU', 'İSTANBUL OUTLET KUNDU', '', '', '', '', 'Müşteri', 'erp', NOW()),
('OVA', 'OVA AMBAR', '', '', '', '', 'Müşteri', 'erp', NOW()),
('OVA AMBAR', 'MVR KARGO TASIMACILIK DAĞITIM DEPOCULUK HİZ TİC LTD ŞTİ', '', '', 'ANTALYA KURUMLAR', '6490478657', 'Müşteri', 'erp', NOW()),
('OYDAŞ', 'OYDAŞ OYUNCAK İÇ VE DIŞ TİC LTD ŞTİ', '', '', 'GÜNEŞLİ', '6490398877', 'Tedarikçi', 'erp', NOW()),
('OYUNCAKÇI', 'OYUNCAKÇI DEDE - GÜLİZAR YILMAZ', '', '', 'ÜÇKAPILAR', '15170588814', 'Müşteri', 'erp', NOW()),
('OZAN', 'OZAN MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('OZPINAR', 'ÖZPINAR MARKET - ESHABİL KARAPINAR', '', '', 'KALEKAPI', '40111413948', 'Müşteri', 'erp', NOW()),
('ÖMER BEDRİ KÜRÜM', 'ÖMER BEDRİ KÜRÜM - EDREMİT', '', '', '', '', 'Müşteri', 'erp', NOW()),
('P', 'PEŞİN SATIŞLAR', '', '', '', '', 'Müşteri', 'erp', NOW()),
('PARAŞÜT', 'PARAŞÜT MARKET - BURCU YILDIRIM', '', '', 'KUMLUCA', '16469305396', 'Müşteri', 'erp', NOW()),
('PASTACI', 'PASTACI TOMBUL - FATMANA ADRASAN', '', '', 'KUMLUCA', '30562010568', 'Müşteri', 'erp', NOW()),
('PAZARAMA', 'PAZARAMA - GÜRBÜZ OYUNCAK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('PİRAMİT', 'PİRAMİT MARKET - ŞERİF GÜNGÖR', '', '', 'KEMER', '23953410344', 'Müşteri', 'erp', NOW()),
('POL', 'POLESİE TR OYUNCAK SAN. VE TİC LTD ŞTİ', '', '', 'SİNOP', '732 144 498 48', 'Tedarikçi', 'erp', NOW()),
('POL-EMY', 'EMY GRUP TEKSTİL SAN VE DIŞ TİC LTD ŞTİ', '', '', 'GERZE', '3340572572', 'Tedarikçi', 'erp', NOW()),
('PORT', 'PORT NATURE OTEL', '', '', '', '', 'Müşteri', 'erp', NOW()),
('PORT-AYDINBEY-BOĞAZKENT', 'PORT - BOĞAZKENT AYDINBEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('PORT-AYDINBEY-KADRİYE', 'PORT - KADRİYE AYDINBEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('PORT-FUNSUN', 'PORT - FUN SUN - ARMAS OTEL', '', '', '', '', 'Müşteri', 'erp', NOW()),
('POŞET', 'MUHTELİF MÜŞTERİLER', '', '', '', '', 'Müşteri', 'erp', NOW()),
('PRENSES', 'MONALİSA SPOR MALZEMELERİ', '', '', 'ANTALYA KURUMLAR', '6221591654', 'Müşteri', 'erp', NOW()),
('PRENSES BUTİK', 'PRENSES BUTİK - İBRAHİM AKBULUT', '', '', 'SERİK', '16975488132', 'Müşteri', 'erp', NOW()),
('PRESTİJ', 'PRESTİJ OYUNCAK', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('PROCO', 'PROCO PLASTİK SANAYİ VE DIŞ TİCARET AŞ', '', '', 'ERENKÖY', '733 041 9190', 'Müşteri', 'erp', NOW()),
('PTT', 'EPTT AVM - SATIŞI', '', '', '', '', 'Müşteri', 'erp', NOW()),
('PUSULA', 'PUSULA MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('REEL FOAM', 'REEL PLASTIK YALITIM AMBALAJ SAN TIC AS', '', '', 'GAZİEMİR', '734 095 1716', 'Müşteri', 'erp', NOW()),
('REGNUM CARYA', 'REGNUM CARYA', '', '', '', '', 'Müşteri', 'erp', NOW()),
('RETOUCH', 'RETOUCH EVENT - ATİLLA SAĞLAM', '', '', 'KURUMLAR', '7341555908', 'Müşteri', 'erp', NOW()),
('ROSE', 'ROSE MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SAFRAN', 'SAFRAN OTEL MARKETİ - FATMA ZEHRA ŞAMAN', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SARISU 1', '1 NOLU BÜFE SARISU', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SARISU 10', '10 NOLU BÜFE SARISU', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SARISU 2', '2 NOLU BÜFE SARISU', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SARISU 3', '3 NOLU BÜFE SARISU - MUSTAFA VAKİT', '', '', 'ÜÇKAPILAR', '372 942 222 14', 'Müşteri', 'erp', NOW()),
('SARISU 4', '4 NOLU BÜFE SARISU - BAYRAM YÜCE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SARISU 5', '5 NOLU BÜFE SARISU', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SARISU 9', '9 NOLU BÜFE SARISU ANADOLU ÇAM CAFE GÜLAY ŞİMŞEKLER', '', '', 'ÜÇKAPILAR', '17987365152', 'Müşteri', 'erp', NOW()),
('SARITEKELİ', 'SARI TEKELİ MARKET - MUSTAFA SARITEKELİ', '', '', 'SERİK', '13543592888', 'Müşteri', 'erp', NOW()),
('SAYIM', 'SAYIM', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SEBAT', 'SEBAT OYUNCAK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SELÇUK', 'REDS TOPTAN MARKET TUR. TİC. LTD. ŞTİ. SELÇUK SUNTUR', '', '', 'MANAVGAT', '7341713947', 'Müşteri', 'erp', NOW()),
('SELFİE', 'SELFİE PARK TURİZM ANONİM ŞİRKETİ', '', '', 'KURUMLAR', '7600997908', 'Müşteri', 'erp', NOW()),
('SERDAR GERÇELER', 'SERDAR GERÇELER', '', '', 'SERİK', '20116638478', 'Müşteri', 'erp', NOW()),
('SERHAN', 'SERHAN KALAY', '05075554269', '', '', '', 'Müşteri', 'erp', NOW()),
('SERRA', 'SERRA HEDİYELİK - YUSUF GÖRGÜLÜ', '', '', 'SERİK', '21496337296', 'Müşteri', 'erp', NOW()),
('SEVGİ', 'SEVGİ HEDİYELİK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SEYHAN', 'SEYHAN MARKET - SELDA SEYHAN', '', '', 'KALEKAPI', '52456628222', 'Müşteri', 'erp', NOW()),
('SİAM', 'SİAM ELEGANCE HOTELS & SPA BEHAR TURİZM İNŞ EML. TİC. A.Ş.', '', '', 'KURUMLAR', '1600631830', 'Müşteri', 'erp', NOW()),
('SİDE HEDİYELİK', 'SİDE HEDİYELİK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SİDE SULTAN', 'SİDE HEDİYELİK - TAYGUN ŞENKAL', '', 'taygun_senkal@hotmail.com', 'KALEKAPI', '42583321738', 'Müşteri', 'erp', NOW()),
('SİLAHÇILAR', 'SİLAHÇILAR MARKET TURİZM LTD ŞTİ', '', '', 'KUMLUCA', '7701249674', 'Müşteri', 'erp', NOW()),
('SİNKAR', 'SİN-KAR TUR.EML.GID.TAR.ORG.ÇİÇ.İNŞ.MLZM.MATB.YAY. İTH.İHR.SAN.VE TİC.LTD.ŞTİ.', '', '', 'SERİK', '7700393778', 'Müşteri', 'erp', NOW()),
('SKY', 'SKY HEDİYELİK - ÖZGE CİHAN', '', '', 'KEMER', '10756683860', 'Müşteri', 'erp', NOW()),
('SMART', 'SMART PLUS EVENT - CEM BULUT', '', '', '', '', 'Müşteri', 'erp', NOW()),
('STAR', 'STAR SÜPER MARKET - ZÜLEYHA YILDIRIM', '', '', 'KEMER', '29929839416', 'Müşteri', 'erp', NOW()),
('SUNMAN', 'SUNMAN SAN. MAM. İTH. İHR. VE TİC. A.Ş.', '', '', 'KURUMLAR', '7840290416', 'Tedarikçi', 'erp', NOW()),
('SUNSTAR', 'SUNSTAR - SPOR MALZ İTH İHR SAN VE TİC AŞ', '', '', 'ALANYA', '7840318743', 'Müşteri', 'erp', NOW()),
('SUNTAW', 'SUNTAW TEXTİL', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ŞİMŞEK', 'ŞİMŞEK MARKET - AZİZ ŞİMŞEK', '', '', 'KEMER', '378 078 119 04', 'Müşteri', 'erp', NOW()),
('ŞOK', 'ŞOK MARKETLER TİC. AŞ.', '', '', 'KURUMLAR', '8140131899', 'Müşteri', 'erp', NOW()),
('ŞÜKRÜ ŞENGÜL', 'ŞÜKRÜ HAVVA ŞENGÜL - AVENA OTEL ALANYA', '', '', 'ALANYA', '10513652924', 'Müşteri', 'erp', NOW()),
('T', 'TOPTAN SATIŞLAR toptan', '', '', '', '', 'Müşteri', 'erp', NOW()),
('TAHTAKALE', 'TAHTAKALE SPOT CENGIZ OYUNCAK HIRD. MZ. İN. TA. NK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('TANER ÇİÇEK', 'TANER ÇİÇEK', '', '', 'İKİTELLİ', '63211178098', 'Müşteri', 'erp', NOW()),
('TOPKAPI-KREMLİN', 'TOPKAPI-KREMLİN PALACE OTEL MARKETLERİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('TOYS&KİDS', 'TOYS&KİDS - HALE TÜRKÖZ', '', '', 'DÜDEN', '11704652624', 'Müşteri', 'erp', NOW()),
('TOYSAN', 'TOYSAN TEK. OYUNCAK GIDA İNŞ. SAN. VE LTD. ŞTİ.', '', '', 'ESENYURT', '8590979912', 'Müşteri', 'erp', NOW()),
('TREND', 'TRENDYOL - GÜRBÜZ OYUNCAK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('TREND-WORLD', 'TRENDYOL - WORLD TOYS', '', '', '', '', 'Müşteri', 'erp', NOW()),
('TRENDY LARA HOTEL', 'TRENDY LARA HOTEL TÜMBÜLOĞLU TUR. YAT. TİC. AŞ.', '', '', 'MANAVGAT', '8740186718', 'Müşteri', 'erp', NOW()),
('TSV', 'TSV MARKETÇILIK GIDA TEKSTIL TUR. SAN. VE TIC. LTD', '', '', 'KURUMLAR', '8590589414', 'Müşteri', 'erp', NOW()),
('TUGAY ERDOĞAN', 'TUGAY ERDOĞAN - MERVE AMBALAJ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('TURAN', 'TURAN TEKSTİL - ANTALIUM', '', '', '', '', 'Müşteri', 'erp', NOW()),
('TURAN2', 'TURAN TEKSTİL - RMZ MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('TURKUAZ MARKET', 'TURKUAZ MARKET - KADİR KALPAZAN', '', '', 'KEMER', '23006503672', 'Müşteri', 'erp', NOW()),
('TURPET', 'TURPET EGE TURİZM TİCARET A.Ş FETHİYE ŞUBESİ', '', '', 'ANTALYA KURUMLAR', '0011831579', 'Müşteri', 'erp', NOW()),
('UĞUR HEDİYELİK', 'UĞUR HEDİYELİK', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ULAŞ', 'ULAŞ MARKET - MUHAMMET SARI', '', '', 'KEMER', '7460047513', 'Müşteri', 'erp', NOW()),
('ÜMİT', 'ÜMİT MARKET - ÜMİT ÖZKAYNAK', '', '', 'KUMLUCA', '25498183998', 'Müşteri', 'erp', NOW()),
('ÜMİT MARKET', 'ÜMİT MARKET TÜP SU TOPTAN PERAKENDE SATIŞ ÜMİT UTAN', '', '', 'MANAVGAT', '187 484 111 94', 'Müşteri', 'erp', NOW()),
('VARDEM', 'VARDEM OYUNCAK VE HEDIYELIK EŞYA GIDA SN TC LTD ŞT', '', '', 'DAVUTPAŞA', '9220095884', 'Tedarikçi', 'erp', NOW()),
('VERK', 'VERK TURİZM', '', '', 'ALANYA', '9240348007', 'Müşteri', 'erp', NOW()),
('VİKİNG', 'VİKİNG MARKET - ÇAMYUVA', '', '', '', '', 'Müşteri', 'erp', NOW()),
('VİVİ', 'VİVİ TOYS', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('XTREME', 'XTREME EVENT TURİZM ORG. SAN TİC LTD', '', '', 'ANTALYA KURUMLAR VD', '8591065007', 'Müşteri', 'erp', NOW()),
('YALI KIRTASİYE', 'YALI KIRTASİYE - AHMET GENCER', '', '', 'KALEKAPI', '28132062352', 'Müşteri', 'erp', NOW()),
('YALI MARKET', 'YALI MARKET - AYHAN ELMACI', '', '', 'KUMLUCA', '192 343 82158', 'Müşteri', 'erp', NOW()),
('YILDIZ MARKET', 'YILDIZ MARKET - CEMALETTİN GÜLAYDIN', '', '', 'SERİK', '283 000 928 46', 'Müşteri', 'erp', NOW()),
('YİĞİT OYUNCAK', 'SELİN İLKAY KARATAŞ', '', '', 'DÜDEN', '16973915562', 'Müşteri', 'erp', NOW()),
('YUMURCAK', 'YUMURCAK DÜNYASI - SEMİH ALTINTAŞ', '', '', 'KUMLUCA', '245 412 153 96', 'Müşteri', 'erp', NOW()),
('ZAKKUM', 'ZAKKUM MARKET - ÇIRALI', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ZAYİ', 'ZAYİ MALLAR', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ZEHRA', 'ZEHRA KASIMOĞLU', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ZÜMRÜT', 'ZÜMRÜT TEXTİL - MEHMET BAKKAL', '', '', '', '', 'Müşteri', 'erp', NOW()),
('LİZZY', 'LİZZY GAMES - OYUN OYUNCAK AKS İTH İHR SN TİC LTD', '', '', 'ANTALYA KURUMLAR', '6091336430', 'Tedarikçi', 'erp', NOW()),
('TRANSATLANTİK', 'TRANSATLANTİK OTEL - ANIL BEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ELİT', 'ELİT OYUNCAK - ALİ BAŞÇI', '', '', '', '', 'Müşteri', 'erp', NOW()),
('AHMET ÇELEBİOĞLU', 'AHMET ÇELEBİOĞLU', '', '', 'SERİK', '21781327506', 'Müşteri', 'erp', NOW()),
('RÜZGAR BALIKÇILIK', 'RÜZGAR BALIKÇILIK - ELİF BEBEK', '5422607401', '', 'MURATPAŞA', '20857068398', 'Müşteri', 'erp', NOW()),
('AKKUZU', 'AKKUZU OYUNCAK', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('CANDY', 'CANDY SHOP - BELEK DOGA TURIZM SEYAHAT INSAAT  SARRAFLIK EMLAK TARIM SAN VE TIC LTD', '', '', 'SERİK', '1620244377', 'Müşteri', 'erp', NOW()),
('AYLİN', 'YUNUS DALIŞ - AYLİN HANIM', '', '', '', '', 'Müşteri', 'erp', NOW()),
('CSM', 'CSM KIRTASİYE - TURİZM SAN VE TİC A.Ş', '', '', 'ANTALYA KURUMLAR', '2150390599', 'Müşteri', 'erp', NOW()),
('MELF', 'MELFSHOP - HAYRİ BURAK ŞAHİN', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ÇALKAN', 'ÇALKAN İTHALAT', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('DOĞANAY', 'DOĞANAY MARKET - NAGİHAN DOĞANAY', '', '', 'ÜÇKAPILAR', '10913914738', 'Müşteri', 'erp', NOW()),
('LİKİYA', 'LİKİYA MARKET - ERAY SÜMER', '0555 3549102', '', 'KEMER', '54292309778', 'Müşteri', 'erp', NOW()),
('BAŞAK', 'BAŞAK POMPA - BÜLENT AKKAYA', '', '', 'KÜÇÜKKÖY', '6680213828', 'Tedarikçi', 'erp', NOW()),
('CORNER', 'CORNER BELEK HEDİYELİK ÜRÜNLERİ GIDA TURİZM İNŞAAT EMLAP PAZ İTH İHR SAN VE TİC LTD', '', '', 'SERİK', '2121062640', 'Müşteri', 'erp', NOW()),
('CESARS', 'CESARS TEMPLE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('AKÇAGERME', 'AKÇAGERME PLAJI - AYHAN ÇIRAK', '', '', 'KAŞ', '20221350364', 'Müşteri', 'erp', NOW()),
('SALKIM', 'SALKIM MARKET - EMRAH KILIÇ', '', '', 'ÜÇKAPILAR', '22270916942', 'Müşteri', 'erp', NOW()),
('AYDEMİR MARKET', 'AYDEMİR MARKET - SAİT GÖKHAN AYDEMİR', '', '', 'ÜÇKAPILAR', '17878158498', 'Müşteri', 'erp', NOW()),
('ALİS MALL', 'ALİS MALL - ADEM ŞETTAH', '', '', 'KALEKAPI', '10360775470', 'Müşteri', 'erp', NOW()),
('SÜLEYMAN ÇELİK', 'SÜLEYMAN ÇELİK', '', '', 'SERİK', '19798394864', 'Müşteri', 'erp', NOW()),
('MOD', 'MOD MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KRAL', 'KRAL HEDİYELİK OYUNCAK - ÇETİN ÖZER', '', '', 'ÜÇKAPILAR', '22177210068', 'Müşteri', 'erp', NOW()),
('YILDIZMİMARİ', 'BÜYÜK ÇALTICAK - YILDIZ MİMARİ TASARIM İNŞ. TUR.', '', '', 'MARMARA KURUMLAR', '6070345881', 'Müşteri', 'erp', NOW()),
('LİMON', 'LİMON OYUNCAK', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('YİĞİT', 'YİĞİT MARKET - FİNİKE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SAHİL', 'SAHİL MARKET - FİNİKE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KARATAŞ', 'KARATAŞ AYAKKABI - FİNİKE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('LİDER', 'LİDER TİCARET - DEMRE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('VOYNN', 'VOYNN MARKET - GIDA TURZ TİC LTD ŞTİ', '', '', 'DEMRE', '9251887227', 'Müşteri', 'erp', NOW()),
('BAYCAN', 'BAYCAN MARKET - KAŞ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('YILMAZLAR', 'YILMAZLAR GIDA TURİZM SAN. TİC. LTD. ŞTİ.', '', '', 'KAŞ', '9780093425', 'Müşteri', 'erp', NOW()),
('ERSİN BUTİK', 'ERSİN BUTİK - BORA YİĞİT', '', '', 'KAŞ', '20305631662', 'Müşteri', 'erp', NOW()),
('YAŞAROĞLU', 'YAŞAROĞLU MARKET - FİNİKE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ÖLÜDENİZ CARREFOUR', 'HAZER SEYAHAT TUR. TAŞ.İNŞ.SAN.VE LTD.ŞTİ.', '', '', 'FETHİYE', '4600347523', 'Müşteri', 'erp', NOW()),
('AHMET KAYA', 'AHMET KAYA - AKFA MARKET', '', '', 'KAŞ MAL MÜDÜRLÜĞÜ', '46783669324', 'Müşteri', 'erp', NOW()),
('ZONGULDAK', 'HALİKARNAS AKVARYUM - CÜNEYT AKBAŞ ZONGULDAK', '0 544 556 49 43', '', '', '', 'Müşteri', 'erp', NOW()),
('NAFİZE', 'NAFİZE MISTIK', '', '', 'MANAVGAT', '27958104758', 'Müşteri', 'erp', NOW()),
('KONCAK', 'KONCAK MARKET - BELDİBİ 2', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ÜZÜMLÜ', 'ÜZÜMLÜ MARKET - HÜSEYİN İSTEKLİ', '', '', 'KAŞ MAL MÜDÜRLÜĞÜ', '29338046498', 'Müşteri', 'erp', NOW()),
('ODAK', 'ODAK MARKET - YUNUS ÇIRALI', '', '', 'KAŞ MAL MÜDÜRLÜĞÜ', '13333579150', 'Müşteri', 'erp', NOW()),
('EREN MARKET', 'EREN MARKET - NERMİN DURAN', '', '', 'MANAVGAT', '32438239868', 'Müşteri', 'erp', NOW()),
('DESTAN', 'DESTAN GRUP GIDA TUR. İNŞ.EML. SAN. VE TİC.LTD.ŞTİ', '', '', 'KAŞ', '2931139139', 'Müşteri', 'erp', NOW()),
('YILDIZ KIRTASİYE', 'YILDIZ KIRTASİYE - ZÜLFE YILDIZ', '', '', 'KAŞ', '60277219598', 'Müşteri', 'erp', NOW()),
('ÇINAR MARKET', 'ÇINAR MARKET - MUSTAFA KAVCAR', '', '', 'KAŞ', '25099187258', 'Müşteri', 'erp', NOW()),
('ÇUKURBAĞ', 'ÇUKURBAĞ MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ŞENDOĞAN', 'ŞENDOĞAN MARKET', '', '', 'SERİK', '8040257396', 'Müşteri', 'erp', NOW()),
('CANDY CRUSH', 'CANDY CRUSH MARKET - ULAŞ TURAN', '', '', 'KALEKAPI', '19097355122', 'Müşteri', 'erp', NOW()),
('TURPET-2', 'TURPET EGE TURİZM TİCARET A.Ş GAZİ BULVARI ŞUBESİ', '', '', 'ANTALYA KURUMLAR', '0011831579', 'Müşteri', 'erp', NOW()),
('ASA', 'XML BAYİ ASA CENTER - SEDA ÇETİN', '', '', '49693601828', 'MANAVGAT', 'Müşteri', 'erp', NOW()),
('ERSİN', 'ERSİN USLU', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BELCONTİ', 'BELCONTİ OTEL - BÜLENT GİRİŞİT', '', '', '', '', 'Müşteri', 'erp', NOW()),
('MMX', 'MİKROMAX TOYS', '', '', 'BEYLİKDÜZÜ', '6210983801', 'Tedarikçi', 'erp', NOW()),
('BUĞRA', 'BUĞRA ABİ', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('EMRE MARKET', 'EMRE MARKET', '', '', 'KAŞ', '23746232504', 'Müşteri', 'erp', NOW()),
('NAZMİ YILDIZ', 'NAZMİ YILDIZ - ORİON', '', '', 'KALEKAPI', '45544480048', 'Müşteri', 'erp', NOW()),
('HAPPY', 'XML - HAPPY JUNİOR - KAAN HAKANHAN ACER', '', '', 'DÜDEN', '34282756300', 'Müşteri', 'erp', NOW()),
('LİBERTY', 'LİBERTY OTEL MARKET  IŞIK TALYA TURİZM LTD ŞTİ', '', '', 'AKSU', '4680566767', 'Müşteri', 'erp', NOW()),
('ALTINANAHTAR', 'ERTUĞRUL - ALTIN ANAHTAR', '', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-SİMENDAM', 'SİMENDAM MARKET - OSMAN TAŞDEMİR', '05061797536', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-NATİSER', 'NATİSER KOZMETİK - SİNAN ERDOĞAN', '0533 614 54 58', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-İSTANBUL PAZARI', 'İSTANBUL PAZARI - IŞIL ÖZAKIN', '0 536 833 37 19', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-HELLO07', 'HELLO 07 MARKET - UMUT TURAÇ', '05386802837', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-REİS', 'REİS MARKET - GÜLİSTAN KELEZLİ', '0532 789 2691', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-VENÜS', 'VENÜS MARKET PEGASUS OTEL - ERSİN OLGUN', '0541 858 6007', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-DİNÇLER', 'DİNÇLER MARKET - LÜTFULLAH DİNÇ', '0552 653 8820', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-FİDANCILIK', 'FİDANCILIK MARKET - İSMAİL İSKEÇ', '0530 397 4887', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ÖZLEM', 'ÖZLEM MARKET - SİNAN DEMİR', '543 675 2063', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-OLİVE NATURAL', 'OLİVE NATURAL BAZAAR - NEVZATCAN BEY', '0553 136 1600', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ALARA', 'ALARA MARKET HEDİYELİK - AYŞE HEDEF', '0535 335 89 71', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-SADULLAH', 'SADULLAH OĞLU TURZ - GREEN GARDEN OTEL - HÜLYA HNM', '0535 549 35 00', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-CLUB TURTAŞ', 'CLUB TURTAŞ HOTEL - SERKAN DOĞANGÜN', '05327107807', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ELVİN', 'ELVİN SÜPERMARKET', '0 536 775 78 11', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-MİRDA', 'MİRDA MARKET - YÜKSEL BAKIR', '0 541 212 63 09', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-TEKİNOĞLU', 'TEKİNOĞLU KUYUMCULUK - KASIM TEKİN', '0 536 554 39 27', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-SARAÇOĞLU', 'SARAÇOĞLU GİYİM - HARUN SARAÇOĞLU', '5547358946', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ELİTE MARKET', 'ELİTE MARKET - AHMET GÖNÜLALAN', '535 480 72 33', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-CONCORDECELES', 'CONCORDE CELES - MÜGE ÇAKICI', '05466366514', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-VİTAMİN MARKET', 'VİTAMİN MARKET - ZEKİ DAĞ', '0 545 342 20 66', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-TEKİNMARKET2', 'TEKİN MARKET 2 - MEHMET TEKİN', '0 536 894 80 78', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-TEKİNMARKETBUTİK', 'TEKİN MARKET BUTİK - İSMAİL TEKİN', '0 536 574 49 10', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-DENİZKIZI', 'DENİZ KIZI MARKET - ÇETİN ERÇETİN', '0 537 291 35 03', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-GMMARKET', 'FATİH MEHMET GÖRGÜLÜ', '05415073255', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ESERBOZKURT', 'ESER HEDİYELİK', '05451710707', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-KERİMYALCİN', 'YALÇIN MANAV MARKET', '05347871159', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-EUROPA', 'EUROPA MARKET - YULIIA AKILE', '0 554 198 07 01', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-CLUPDEMOTEL', 'CLUP DEM OTEL - MESTAN ÇAĞLAR', '0 530 547 50 54', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ÇINAR MARKET', 'ÇINAR MARKET - EROL ALTUN', '0536 667 0562', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ÖZYİĞİT', 'ÖZYİĞİT AKARYAKIT - HÜSEYİN ÖZYİĞİT', '0532 772 7155', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ÇAMLICA MARKET', 'ÇAMLICA MARKET - VELİ AĞAOĞLU', '0536 636 4811', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-BERA OTEL', 'BERA OTEL MARKETİ - SERHAN ÖZER', '05336665368', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ADENYA OTEL', 'ADENYA OTEL MARKET SERHAN ÖZER', '05336665368', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ERGİN MARKET', 'ERGİN MARKET - ÜTOPYA OTEL - SELAMİ ERGİN', '0532 776 0710', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-HAKANGÜZEL', 'HAKAN GÜZEL', '05464924890', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-AKAN MARKET', 'AKAN MARKET - HÜSEYİN AKAN', '533 527 0043', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-NURISARIKAYA', 'NURİ BAHARAT', '05337788329', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-DOĞANCENTER', 'DOĞAN CENTER - UĞUR BAŞ', '0 535 799 58 98', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-UTKUGELES', 'UTKU MARKET SEÇ MARKET', '05446365497', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-TURANGIDA', 'TURAN GIDA - HÜSEYİN PEKER', '0507 555 44 44', '', '', '', 'Müşteri', 'erp', NOW()),
('PEKER', 'PEKER İTRİYAT', '', '', 'ALANYA', '7250176799', 'Müşteri', 'erp', NOW()),
('PKR-AZURA DELUX', 'AZURA DELUX - ERTUĞRUL KURT', '05514294740', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ROBİN PLATİNYUM', 'ROBİN PLATİNYUM - ERDEM GÖRGÜLÜ', '05514294740', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ALİ BABA SÜPERMARKET', 'ALİ BABA SÜPER MARKET - AYHAN ŞENEL', '531 823 4971', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-BLUE STAR', 'BLUE STAR OTEL MARKETİ - DENİZ GÜLCAN', '0532 474 5113', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-UMAY', 'UMAY MARKET - ALİ ŞENEL', '0507 532 2830', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ALARA PETROL', 'ALARA PETROL - METİN BAYSAL', '0532 230 5965', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-BAYKAL MARKET', 'BAYKAL MARKET - İSMAİL BAYKAL', '0533 451 6226', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ALL IN SUPERMARKET', 'ALL IN SUPERMARKET - EREN ÇINAR', '0538 234 8026', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-MERİH MARKET', 'MERİH MARKET - MERİH MARKET', '0506 300 0813', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ARIM MARKET', 'ARIM MARKET', '0535 846 6831', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-SEÇ-BUĞRA', 'SEÇ MARKET - BUĞRA ÖZKUBAT', '0506 558 2200', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ÜTOPYA-OTEL MARKET', 'ÜTOPYA OTEL MARKETİ - YURDA ÖZKUBAT', '0532 427 71 55', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-QUATROOTEL', 'QUATRO OTEL - İBRAHİM ÖRKMEN', '0 537 410 40 74', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-ESAS PERAKENDE', 'ESAS PERAKENDECİLİK SEÇ MARKET - SERCAN AĞYAR', '0543 254 3143', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-07SERİK', '07 SERİK DAMAKTADI MARKET', '05332826167', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-HOLİDAY MARKET', 'HOLİDAY MARKET - ZÖHRE ÇAKMAK', '0 542 560 21 93', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-MY HOME', 'MY HOME MARKET - HÜSEYİN KOÇAK', '0 532 472 12 22', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-SEÇ-LEYLAGÜVEN', 'SEÇ MARKET - LEYLA GÜVEN', '0536 940 9246', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-GÜVENOĞLU', 'GÜVENOĞLU CİKCİLLİ - ÜMİT GÜVEN', '0536 940 9246', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-GÜVENOĞLU MARKET', 'GÜVENOĞLU MARKETÇİLİK - RAMAZAN GÜVEN', '0530 236 1808', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-SEÇ-GÜVEN-ÇARŞI', 'SEÇ MARKET GÜVENOĞLU ÇARŞI - ÜNAL GÜVEN', '0533 119 1922', '', '', '', 'Müşteri', 'erp', NOW()),
('PKR-REPLİNE', 'REPLİNE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GYPSOPHİLA', 'GYPSOPHİLA - TURAN TURİZM TİC. LTD ŞTİ', '0 533 966 68 37', '', 'KEMER', '8690231407', 'Müşteri', 'erp', NOW()),
('PKR-ASİA', 'ASİA SÜPERMARKET  EMRULLAH KUMRU', '0554 648 45 00', '', '', '', 'Müşteri', 'erp', NOW()),
('GLOBAL', 'GLOBAL TOYS - SAN TİC LTD ŞTİ', '', '', 'BEŞ OCAK', '3961197728', 'Tedarikçi', 'erp', NOW()),
('PKR-ÇELİK HEDİYELİK', 'ÇELİK HEDİYELİK MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('BOHEM', 'BOHEM BEACH -', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ULUS', 'ULUS OYUNCAK', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('PEHLİVAN', 'ANDİAKE BEACH CLUB  ÇETİN PEHLİVAN', '05322280408', '', 'DEMRE', '12043644486', 'Müşteri', 'erp', NOW()),
('TOPALAN', 'OSMAN TOPALAN', '', '', 'KALEKAPI', '30740400716', 'Müşteri', 'erp', NOW()),
('ÇEŞ MARKET', 'ÇEŞ MARKET - FETHİYE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('AYBÜKEM', 'AYBÜKEM MARKET - SERTAL YAŞAR', '', '', 'FETHİYE', '248 004 027 96', 'Müşteri', 'erp', NOW()),
('AKDENİZ', 'AKDENİZ MARKET - AYŞE TOPÇU', '', '', 'FETHİYE', '40921865296', 'Müşteri', 'erp', NOW()),
('SEÇİL', 'SEÇİL MARKET - FETHİYE - ÇALIŞ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('KAYA PALAZZO', 'KAYA PALAZZO - MESUT ERGENÇ', '', '', 'SERİK', '46636268438', 'Müşteri', 'erp', NOW()),
('SEZPET-1', 'SEZPET PETROL - KÜLTÜR', '', '', 'ANTALYA KURUMLAR', '7690536274', 'Müşteri', 'erp', NOW()),
('SEZPET-2', 'SEZPET PETROL - FABRİKALAR', '', '', 'ANTALYA KURUMLAR', '7690536274', 'Müşteri', 'erp', NOW()),
('SEZPET-3', 'YEŞİLBAYIR PETROL', '', '', 'ANTALYA KURUMLAR', '9500481101', 'Müşteri', 'erp', NOW()),
('MEHMET AKYÜZ', 'MEHMET AKYÜZ', '', '', 'KEMER', '23482698114', 'Müşteri', 'erp', NOW()),
('MÜŞTERİ', 'MÜŞTERİ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GÜLŞEN', 'GÜLŞEN AY', '05422428202', '', 'SERİK', '1060463243', 'Müşteri', 'erp', NOW()),
('UNİCORN', 'MURAT VATANSEVER', '', '', 'FETHİYE', '43969474512', 'Müşteri', 'erp', NOW()),
('NERGİZ', 'NERGİZ MARKET - KALKAN', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ÖMER YILDIZ', 'ÖMER YILDIZ - YILDIZ MARKET', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SEZDEN', 'SEZDEN TURİZM SEYAHAT REK TİC VE SAN LTD ŞTİ', '', '', 'ANTALYA KURUMLAR', '7671103780', 'Müşteri', 'erp', NOW()),
('SMART-2', 'SMART EVENT - ATAKAN BEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ATEŞOĞULLARI', 'ATEŞOĞULLARI PETROL - RESUL ATEŞ', '', '', 'SERİK', '20998353896', 'Müşteri', 'erp', NOW()),
('ADİN OTEL', 'ADİN OTEL - NML TURİZM TARIM SAN. VE TİC. A.Ş.', '', '', 'ALANYA', '6311482603', 'Müşteri', 'erp', NOW()),
('KONYAALTI AKDENİZ', 'KONYAALTI AKDENİZ MARKET - MAKBULE AYŞE TABUR', '', '', 'ÜÇKAPILAR', '25618191766', 'Müşteri', 'erp', NOW()),
('YİĞİTOĞLU', 'YİĞİTOĞLU MARKET - FETHİYE FARALYA', '', '', '', '', 'Müşteri', 'erp', NOW()),
('OVACIK', 'OVACIK MARKET  - MELİHAT UYSAL', '', '', 'FETHİYE', '34312288696', 'Müşteri', 'erp', NOW()),
('ORGANİK', 'ORGANİK - SELİM GEDİKOĞLU', '', '', 'KAŞ', '23176251366', 'Müşteri', 'erp', NOW()),
('EFSANE', 'EFSANE MARKET - ÇAĞRI SAMET SÖNMEZ', '', '', 'KUMLUCA', '23962215718', 'Müşteri', 'erp', NOW()),
('ÇAKRA', 'ÇAKRA KAMPİNG - ÇAĞRI ÖZBAKİ KARA', '', '', 'FETHİYE', '50902564742', 'Müşteri', 'erp', NOW()),
('HİDAYET', 'BİLGE TİCARET - ÖZGE CEYLAN', '', '', 'DÜDEN', '49213258082', 'Müşteri', 'erp', NOW()),
('DENGE', 'DENGE AVM - ALİ BERKE ÇALIŞIR', '', '', 'DEMRE', '32939441500', 'Müşteri', 'erp', NOW()),
('AYAZ', 'AYAZ MARKET RESTAURANT', '', '', 'KUMLUCA', '22891246206', 'Müşteri', 'erp', NOW()),
('TUT', 'TUT GIDA TURZ. SAN. VE TİC. LTD. ŞTİ', '05318834960', '', 'ANTALYA KURUMLAR', '8721162086', 'Müşteri', 'erp', NOW()),
('AYTUĞ', 'AYTUĞ BONCUK MARKET - AYTUĞ BONCUK', '', '', 'KUMLUCA', '12934602816', 'Müşteri', 'erp', NOW()),
('EMİN ÖLMEZ', 'EMİN HER ÇEŞİT UCUZLUK PAZARI - EMİN ÖLMEZ', '', '', 'FETHİYE', '17669640560', 'Müşteri', 'erp', NOW()),
('ADRASAN AVM', 'ADRASAN AVM', '', '', 'KUMLUCA', '13324589274', 'Müşteri', 'erp', NOW()),
('BUDAK', 'BUDAK MARKET - TESİSAT İNŞ TURZ SAN VE TİC LTD', '', '', 'KEMER', '1871513282', 'Müşteri', 'erp', NOW()),
('PROMİL 46', 'PROMİL 46 - GÜLBAY TÜFENK', '', '', 'KUMLUCA V.D', '24688928074', 'Müşteri', 'erp', NOW()),
('REZZA', 'EMİN ASLAN - BELDİBİ', '', '', 'KEMER', '10393475170', 'Müşteri', 'erp', NOW()),
('BADEM', 'BADEM MARKET - ŞERİFE KARAKAYA', '', '', 'KAŞ', '21166318716', 'Müşteri', 'erp', NOW()),
('DUCALE', 'DUCALE OTEL - BÜLENT GİRİŞİT', '', '', '', '', 'Müşteri', 'erp', NOW()),
('SİNEM ÖZGE HAVUZ', 'SİNEM ÖZGE HAVUZ', '0 545 643 71 11', '', 'ÜÇKAPILAR', '46141463526', 'Müşteri', 'erp', NOW()),
('ENES', 'ENES DEMİRALAY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ZAFER', 'ZAFER BEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('MEHMET', 'MEHMET ÇOLAK - İZMİR', '', '', '', '', 'Müşteri', 'erp', NOW()),
('ÇETİNER', 'ÇETİNER MARKET - KADER SÜLEYMAN ÇETİNER', '0539 851 2305', '', 'KUMLUCA', '12469617736', 'Müşteri', 'erp', NOW()),
('ZUZU', 'ZUZU OYUNCAK HEDİYELİK - RASHAD GASIMOV', '', '', 'KALEKAPI', '99359761762', 'Müşteri', 'erp', NOW()),
('ÇINAR ZÜCCACİYE', 'ÇINAR ZÜCCACİYE - İSMAİL YENER', '05368982606', '', '', '', 'Tedarikçi', 'erp', NOW()),
('ZEYNEP', 'ZEYNEP HANIM PEKER', '', '', '', '', 'Müşteri', 'erp', NOW()),
('AKÇİÇEK', 'AKÇİÇEK OYUNCAK KIRTASİYE', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GÜL MARKET', 'GÜL MARKET - IŞIK SEMERCİ', '', '', '7600218594', 'FETHİYE', 'Müşteri', 'erp', NOW()),
('ŞORTÇU', 'MEHMET KARAKOÇ - ŞORTÇU', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('MİGROS', 'MİGROS TİCARET A.Ş', '', '', 'BÜYÜK MÜKELLEFLER', '6220529513', 'Müşteri', 'erp', NOW()),
('ÇLK', 'ÇLK  ÇALKAN PLASTİK SAN TİC LTD ŞTİ', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('İZZET', 'PRESTİJ BAZAAR HEDİYELİK İZZET BEY', '', '', '', '', 'Müşteri', 'erp', NOW()),
('GÜNEŞ HEDİYELİK', 'GÜNEŞ HEDİYELİK - TOLGA GÜNEŞ', '', '', '', '', 'Müşteri', 'erp', NOW()),
('MARGAZ', 'MARGAZ MARKET KALKAN', '', '', 'KAŞ', '46837668402', 'Müşteri', 'erp', NOW()),
('DOLU', 'DOLU OYUNCAK KEMAL', '', '', '', '', 'Tedarikçi', 'erp', NOW()),
('ANT-ANAOKULU', 'ANTALYA MURATPAŞA ANAOKULU', '', '', 'KALEKAPI', '2060661577', 'Müşteri', 'erp', NOW())
ON CONFLICT (cari_kodu) DO UPDATE SET
    cari_adi = EXCLUDED.cari_adi,
    telefon = EXCLUDED.telefon,
    eposta = EXCLUDED.eposta,
    vergi_dairesi = EXCLUDED.vergi_dairesi,
    vergi_no = EXCLUDED.vergi_no,
    cari_tipi = EXCLUDED.cari_tipi,
    kaynak = EXCLUDED.kaynak,
    guncelleme_tarihi = NOW();