-- SADECE MÜŞTERİ TİPİ GÜNCELLEME SQL
-- Toplam Kayıt: 462

UPDATE cari_hesaplar AS c
SET cari_tipi = v.yeni_tip,
    guncelleme_tarihi = NOW()
FROM (VALUES 
('07RÜZGAR', 'Müşteri'),
('ABİDİN', 'Müşteri'),
('ACİL', 'Müşteri'),
('ADALYA', 'Tedarikçi'),
('ADRASAN HEDİYELİK', 'Müşteri'),
('AHMET ER', 'Müşteri'),
('AKIN', 'Müşteri'),
('AKSU ÇAMLIK', 'Müşteri'),
('ALİS', 'Müşteri'),
('AMCAM', 'Müşteri'),
('ANDİFLİ', 'Müşteri'),
('ANTALYA KIRTASİYE', 'Müşteri'),
('ANTEVENT', 'Müşteri'),
('ANTİK MARKET', 'Müşteri'),
('ARAS', 'Müşteri'),
('ARIA', 'Müşteri'),
('ARMAĞAN', 'Müşteri'),
('ASPENDOS', 'Müşteri'),
('ASYA', 'Tedarikçi'),
('AVCIOGLU', 'Müşteri'),
('AYDEMİR', 'Tedarikçi'),
('AYHAN ERMEÇ', 'Müşteri'),
('BAHADIR', 'Müşteri'),
('BAHADIR2', 'Müşteri'),
('BAHADIR3', 'Müşteri'),
('BAHADIR4', 'Müşteri'),
('BAYRAK', 'Müşteri'),
('BELEK BEACH OTEL', 'Müşteri'),
('ZAKKUM-BEREKET', 'Müşteri'),
('BEST MARKET', 'Müşteri'),
('BİKİNİ', 'Müşteri'),
('BİM', 'Müşteri'),
('BİRLİK', 'Tedarikçi'),
('BİSART', 'Müşteri'),
('BİZİM OYUNCAK', 'Tedarikçi'),
('BLUE FİSH', 'Müşteri'),
('BONCUK', 'Müşteri'),
('BULVAR', 'Müşteri'),
('BULVAR 3', 'Müşteri'),
('BY ALDİ', 'Müşteri'),
('BYR', 'Müşteri'),
('CANCAN', 'Müşteri'),
('CANEM', 'Tedarikçi'),
('CARELTA', 'Müşteri'),
('CASPER', 'Müşteri'),
('CEMRE', 'Müşteri'),
('CEO', 'Müşteri'),
('CEREN', 'Müşteri'),
('CEREN HEDİYELİK', 'Müşteri'),
('CEYLAN', 'Müşteri'),
('CHAS', 'Müşteri'),
('CRİSTAL', 'Müşteri'),
('CRİSTAL FAMİLY', 'Müşteri'),
('CRİSTAL2', 'Müşteri'),
('ÇERKEZ MARKET', 'Müşteri'),
('ÇINAR', 'Tedarikçi'),
('ÇS', 'Müşteri'),
('ÇS-WORLD', 'Müşteri'),
('D', 'Müşteri'),
('DAĞ', 'Müşteri'),
('DAĞ2', 'Müşteri'),
('DEDE', 'Tedarikçi'),
('DEKOR', 'Tedarikçi'),
('DELFİN1', 'Müşteri'),
('DENİZ ŞAHİN', 'Müşteri'),
('DENİZ TOP', 'Müşteri'),
('DORUK', 'Müşteri'),
('DUAŞ', 'Müşteri'),
('DURAN', 'Müşteri'),
('DURU', 'Tedarikçi'),
('E MARKET', 'Müşteri'),
('EKİCİ TURİZM', 'Müşteri'),
('EKİZ MARKET', 'Müşteri'),
('ELİFHAN', 'Müşteri'),
('EMEL', 'Müşteri'),
('ENFAL', 'Tedarikçi'),
('ERDEM', 'Tedarikçi'),
('ROBİNSON', 'Müşteri'),
('ERKOL', 'Müşteri'),
('EROL ŞAHAN', 'Müşteri'),
('ETHEM', 'Tedarikçi'),
('EUROSHOP', 'Müşteri'),
('FALEZ', 'Müşteri'),
('FARUK GÜR - HAKKARİ', 'Müşteri'),
('FATİH', 'Müşteri'),
('FATİH ÖZCAN', 'Müşteri'),
('FERHAT', 'Tedarikçi'),
('FİYONK', 'Müşteri'),
('GEPETTOYS', 'Tedarikçi'),
('GG', 'Müşteri'),
('GG-WORLD', 'Müşteri'),
('GÖKÇE', 'Müşteri'),
('GÖKER', 'Müşteri'),
('GÖYNÜK', 'Müşteri'),
('GRANDHABER', 'Müşteri'),
('GRANDPARK', 'Müşteri'),
('GREEN', 'Müşteri'),
('GÜL HEDİYELİK', 'Müşteri'),
('GÜNEŞ', 'Müşteri'),
('GÜNEŞCAN', 'Müşteri'),
('GÜNYAPI', 'Müşteri'),
('GÜRBÜZ', 'Müşteri'),
('GÜRBÜZWEB', 'Müşteri'),
('GÜRKAN', 'Müşteri'),
('HAMİT', 'Müşteri'),
('HARUN AKYOL', 'Müşteri'),
('HASDEN', 'Müşteri'),
('HB', 'Müşteri'),
('HB-WORLD', 'Müşteri'),
('HIZLI', 'Müşteri'),
('İDEFİX', 'Müşteri'),
('İDRİS', 'Müşteri'),
('İKİZLER', 'Müşteri'),
('İSMAİL HANTAL', 'Müşteri'),
('İSMET', 'Müşteri'),
('İSTANBUL OUTLET2', 'Müşteri'),
('İSTANBUL TEXTİL', 'Müşteri'),
('JASMİN', 'Müşteri'),
('JOY EVENT', 'Müşteri'),
('JUMBO', 'Müşteri'),
('JUMBO2', 'Müşteri'),
('JUMBO3', 'Müşteri'),
('KALENDER', 'Müşteri'),
('KALKAN KIRTASİYE', 'Müşteri'),
('KAPLAN KIRTASİYE', 'Müşteri'),
('KARA', 'Tedarikçi'),
('KARACAN', 'Müşteri'),
('KARİZMA', 'Müşteri'),
('KARTOY', 'Tedarikçi'),
('KAYA MARKET', 'Müşteri'),
('KEMAL DAĞ', 'Müşteri'),
('KEMBAY', 'Tedarikçi'),
('KEPEZ EKMEK BÜFESİ', 'Müşteri'),
('KERVAN', 'Müşteri'),
('KETSAN', 'Tedarikçi'),
('KETTE', 'Tedarikçi'),
('KETTE-ZÜLKÜF', 'Müşteri'),
('KIZIL', 'Tedarikçi'),
('KIZILZAYİ', 'Müşteri'),
('KK', 'Müşteri'),
('KLADOS', 'Müşteri'),
('KOÇ', 'Müşteri'),
('KOÇAK', 'Müşteri'),
('KOÇAK-2', 'Müşteri'),
('KÖŞEM', 'Müşteri'),
('KUBİLAY', 'Müşteri'),
('KURT', 'Müşteri'),
('KUŞADASI İSA', 'Müşteri'),
('LABOR', 'Müşteri'),
('LAKEYİF', 'Müşteri'),
('LEVENT', 'Müşteri'),
('LEVENT GELGEÇ', 'Müşteri'),
('LİDYA MARKET', 'Müşteri'),
('LİMAK', 'Müşteri'),
('LİSİNYA', 'Müşteri'),
('LOLY', 'Müşteri'),
('M.HANTAL', 'Müşteri'),
('MALİMOĞLU', 'Müşteri'),
('MARDAN', 'Müşteri'),
('MAY', 'Müşteri'),
('MAYA', 'Müşteri'),
('MAZLUM', 'Müşteri'),
('MEHMET FATİH', 'Müşteri'),
('MENTEŞ', 'Müşteri'),
('MİÇO', 'Müşteri'),
('MİLANO', 'Müşteri'),
('MİRA', 'Müşteri'),
('MOOD', 'Müşteri'),
('MUAMMER GÜRKAN', 'Müşteri'),
('MUEM BEBE', 'Müşteri'),
('MURAT DOĞAN', 'Müşteri'),
('MUSTAFA SILAMOR', 'Müşteri'),
('N11', 'Müşteri'),
('N11WORLD', 'Müşteri'),
('NAFİ', 'Müşteri'),
('NATUR', 'Müşteri'),
('NURİYE SEVİNÇ', 'Müşteri'),
('OKÇU AV ELAZIĞ', 'Müşteri'),
('ONYIL', 'Müşteri'),
('OPTİMUM', 'Müşteri'),
('OPUS', 'Müşteri'),
('ORMANCI', 'Müşteri'),
('OSMAN GEZER', 'Müşteri'),
('OUTLET KUNDU', 'Müşteri'),
('OVA', 'Müşteri'),
('OVA AMBAR', 'Müşteri'),
('OYDAŞ', 'Tedarikçi'),
('OYUNCAKÇI', 'Müşteri'),
('OZAN', 'Müşteri'),
('OZPINAR', 'Müşteri'),
('ÖMER BEDRİ KÜRÜM', 'Müşteri'),
('P', 'Müşteri'),
('PARAŞÜT', 'Müşteri'),
('PASTACI', 'Müşteri'),
('PAZARAMA', 'Müşteri'),
('PİRAMİT', 'Müşteri'),
('POL', 'Tedarikçi'),
('POL-EMY', 'Tedarikçi'),
('PORT', 'Müşteri'),
('PORT-AYDINBEY-BOĞAZKENT', 'Müşteri'),
('PORT-AYDINBEY-KADRİYE', 'Müşteri'),
('PORT-FUNSUN', 'Müşteri'),
('POŞET', 'Müşteri'),
('PRENSES', 'Müşteri'),
('PRENSES BUTİK', 'Müşteri'),
('PRESTİJ', 'Tedarikçi'),
('PROCO', 'Müşteri'),
('PTT', 'Müşteri'),
('PUSULA', 'Müşteri'),
('REEL FOAM', 'Müşteri'),
('REGNUM CARYA', 'Müşteri'),
('RETOUCH', 'Müşteri'),
('ROSE', 'Müşteri'),
('SAFRAN', 'Müşteri'),
('SARISU 1', 'Müşteri'),
('SARISU 10', 'Müşteri'),
('SARISU 2', 'Müşteri'),
('SARISU 3', 'Müşteri'),
('SARISU 4', 'Müşteri'),
('SARISU 5', 'Müşteri'),
('SARISU 9', 'Müşteri'),
('SARITEKELİ', 'Müşteri'),
('SAYIM', 'Müşteri'),
('SEBAT', 'Müşteri'),
('SELÇUK', 'Müşteri'),
('SELFİE', 'Müşteri'),
('SERDAR GERÇELER', 'Müşteri'),
('SERHAN', 'Müşteri'),
('SERRA', 'Müşteri'),
('SEVGİ', 'Müşteri'),
('SEYHAN', 'Müşteri'),
('SİAM', 'Müşteri'),
('SİDE HEDİYELİK', 'Müşteri'),
('SİDE SULTAN', 'Müşteri'),
('SİLAHÇILAR', 'Müşteri'),
('SİNKAR', 'Müşteri'),
('SKY', 'Müşteri'),
('SMART', 'Müşteri'),
('STAR', 'Müşteri'),
('SUNMAN', 'Tedarikçi'),
('SUNSTAR', 'Müşteri'),
('SUNTAW', 'Müşteri'),
('ŞİMŞEK', 'Müşteri'),
('ŞOK', 'Müşteri'),
('ŞÜKRÜ ŞENGÜL', 'Müşteri'),
('T', 'Müşteri'),
('TAHTAKALE', 'Müşteri'),
('TANER ÇİÇEK', 'Müşteri'),
('TOPKAPI-KREMLİN', 'Müşteri'),
('TOYS&KİDS', 'Müşteri'),
('TOYSAN', 'Müşteri'),
('TREND', 'Müşteri'),
('TREND-WORLD', 'Müşteri'),
('TRENDY LARA HOTEL', 'Müşteri'),
('TSV', 'Müşteri'),
('TUGAY ERDOĞAN', 'Müşteri'),
('TURAN', 'Müşteri'),
('TURAN2', 'Müşteri'),
('TURKUAZ MARKET', 'Müşteri'),
('TURPET', 'Müşteri'),
('UĞUR HEDİYELİK', 'Müşteri'),
('ULAŞ', 'Müşteri'),
('ÜMİT', 'Müşteri'),
('ÜMİT MARKET', 'Müşteri'),
('VARDEM', 'Tedarikçi'),
('VERK', 'Müşteri'),
('VİKİNG', 'Müşteri'),
('VİVİ', 'Tedarikçi'),
('XTREME', 'Müşteri'),
('YALI KIRTASİYE', 'Müşteri'),
('YALI MARKET', 'Müşteri'),
('YILDIZ MARKET', 'Müşteri'),
('YİĞİT OYUNCAK', 'Müşteri'),
('YUMURCAK', 'Müşteri'),
('ZAKKUM', 'Müşteri'),
('ZAYİ', 'Müşteri'),
('ZEHRA', 'Müşteri'),
('ZÜMRÜT', 'Müşteri'),
('LİZZY', 'Tedarikçi'),
('TRANSATLANTİK', 'Müşteri'),
('ELİT', 'Müşteri'),
('AHMET ÇELEBİOĞLU', 'Müşteri'),
('RÜZGAR BALIKÇILIK', 'Müşteri'),
('AKKUZU', 'Tedarikçi'),
('CANDY', 'Müşteri'),
('AYLİN', 'Müşteri'),
('CSM', 'Müşteri'),
('MELF', 'Müşteri'),
('ÇALKAN', 'Tedarikçi'),
('DOĞANAY', 'Müşteri'),
('LİKİYA', 'Müşteri'),
('BAŞAK', 'Tedarikçi'),
('CORNER', 'Müşteri'),
('CESARS', 'Müşteri'),
('AKÇAGERME', 'Müşteri'),
('SALKIM', 'Müşteri'),
('AYDEMİR MARKET', 'Müşteri'),
('ALİS MALL', 'Müşteri'),
('SÜLEYMAN ÇELİK', 'Müşteri'),
('MOD', 'Müşteri'),
('KRAL', 'Müşteri'),
('YILDIZMİMARİ', 'Müşteri'),
('LİMON', 'Tedarikçi'),
('YİĞİT', 'Müşteri'),
('SAHİL', 'Müşteri'),
('KARATAŞ', 'Müşteri'),
('LİDER', 'Müşteri'),
('VOYNN', 'Müşteri'),
('BAYCAN', 'Müşteri'),
('YILMAZLAR', 'Müşteri'),
('ERSİN BUTİK', 'Müşteri'),
('YAŞAROĞLU', 'Müşteri'),
('ÖLÜDENİZ CARREFOUR', 'Müşteri'),
('AHMET KAYA', 'Müşteri'),
('ZONGULDAK', 'Müşteri'),
('NAFİZE', 'Müşteri'),
('KONCAK', 'Müşteri'),
('ÜZÜMLÜ', 'Müşteri'),
('ODAK', 'Müşteri'),
('EREN MARKET', 'Müşteri'),
('DESTAN', 'Müşteri'),
('YILDIZ KIRTASİYE', 'Müşteri'),
('ÇINAR MARKET', 'Müşteri'),
('ÇUKURBAĞ', 'Müşteri'),
('ŞENDOĞAN', 'Müşteri'),
('CANDY CRUSH', 'Müşteri'),
('TURPET-2', 'Müşteri'),
('ASA', 'Müşteri'),
('ERSİN', 'Müşteri'),
('BELCONTİ', 'Müşteri'),
('MMX', 'Tedarikçi'),
('BUĞRA', 'Tedarikçi'),
('EMRE MARKET', 'Müşteri'),
('NAZMİ YILDIZ', 'Müşteri'),
('HAPPY', 'Müşteri'),
('LİBERTY', 'Müşteri'),
('ALTINANAHTAR', 'Müşteri'),
('PKR-SİMENDAM', 'Müşteri'),
('PKR-NATİSER', 'Müşteri'),
('PKR-İSTANBUL PAZARI', 'Müşteri'),
('PKR-HELLO07', 'Müşteri'),
('PKR-REİS', 'Müşteri'),
('PKR-VENÜS', 'Müşteri'),
('PKR-DİNÇLER', 'Müşteri'),
('PKR-FİDANCILIK', 'Müşteri'),
('PKR-ÖZLEM', 'Müşteri'),
('PKR-OLİVE NATURAL', 'Müşteri'),
('PKR-ALARA', 'Müşteri'),
('PKR-SADULLAH', 'Müşteri'),
('PKR-CLUB TURTAŞ', 'Müşteri'),
('PKR-ELVİN', 'Müşteri'),
('PKR-MİRDA', 'Müşteri'),
('PKR-TEKİNOĞLU', 'Müşteri'),
('PKR-SARAÇOĞLU', 'Müşteri'),
('PKR-ELİTE MARKET', 'Müşteri'),
('PKR-CONCORDECELES', 'Müşteri'),
('PKR-VİTAMİN MARKET', 'Müşteri'),
('PKR-TEKİNMARKET2', 'Müşteri'),
('PKR-TEKİNMARKETBUTİK', 'Müşteri'),
('PKR-DENİZKIZI', 'Müşteri'),
('PKR-GMMARKET', 'Müşteri'),
('PKR-ESERBOZKURT', 'Müşteri'),
('PKR-KERİMYALCİN', 'Müşteri'),
('PKR-EUROPA', 'Müşteri'),
('PKR-CLUPDEMOTEL', 'Müşteri'),
('PKR-ÇINAR MARKET', 'Müşteri'),
('PKR-ÖZYİĞİT', 'Müşteri'),
('PKR-ÇAMLICA MARKET', 'Müşteri'),
('PKR-BERA OTEL', 'Müşteri'),
('PKR-ADENYA OTEL', 'Müşteri'),
('PKR-ERGİN MARKET', 'Müşteri'),
('PKR-HAKANGÜZEL', 'Müşteri'),
('PKR-AKAN MARKET', 'Müşteri'),
('PKR-NURISARIKAYA', 'Müşteri'),
('PKR-DOĞANCENTER', 'Müşteri'),
('PKR-UTKUGELES', 'Müşteri'),
('PKR-TURANGIDA', 'Müşteri'),
('PEKER', 'Müşteri'),
('PKR-AZURA DELUX', 'Müşteri'),
('PKR-ROBİN PLATİNYUM', 'Müşteri'),
('PKR-ALİ BABA SÜPERMARKET', 'Müşteri'),
('PKR-BLUE STAR', 'Müşteri'),
('PKR-UMAY', 'Müşteri'),
('PKR-ALARA PETROL', 'Müşteri'),
('PKR-BAYKAL MARKET', 'Müşteri'),
('PKR-ALL IN SUPERMARKET', 'Müşteri'),
('PKR-MERİH MARKET', 'Müşteri'),
('PKR-ARIM MARKET', 'Müşteri'),
('PKR-SEÇ-BUĞRA', 'Müşteri'),
('PKR-ÜTOPYA-OTEL MARKET', 'Müşteri'),
('PKR-QUATROOTEL', 'Müşteri'),
('PKR-ESAS PERAKENDE', 'Müşteri'),
('PKR-07SERİK', 'Müşteri'),
('PKR-HOLİDAY MARKET', 'Müşteri'),
('PKR-MY HOME', 'Müşteri'),
('PKR-SEÇ-LEYLAGÜVEN', 'Müşteri'),
('PKR-GÜVENOĞLU', 'Müşteri'),
('PKR-GÜVENOĞLU MARKET', 'Müşteri'),
('PKR-SEÇ-GÜVEN-ÇARŞI', 'Müşteri'),
('PKR-REPLİNE', 'Müşteri'),
('GYPSOPHİLA', 'Müşteri'),
('PKR-ASİA', 'Müşteri'),
('GLOBAL', 'Tedarikçi'),
('PKR-ÇELİK HEDİYELİK', 'Müşteri'),
('BOHEM', 'Müşteri'),
('ULUS', 'Tedarikçi'),
('PEHLİVAN', 'Müşteri'),
('TOPALAN', 'Müşteri'),
('ÇEŞ MARKET', 'Müşteri'),
('AYBÜKEM', 'Müşteri'),
('AKDENİZ', 'Müşteri'),
('SEÇİL', 'Müşteri'),
('KAYA PALAZZO', 'Müşteri'),
('SEZPET-1', 'Müşteri'),
('SEZPET-2', 'Müşteri'),
('SEZPET-3', 'Müşteri'),
('MEHMET AKYÜZ', 'Müşteri'),
('MÜŞTERİ', 'Müşteri'),
('GÜLŞEN', 'Müşteri'),
('UNİCORN', 'Müşteri'),
('NERGİZ', 'Müşteri'),
('ÖMER YILDIZ', 'Müşteri'),
('SEZDEN', 'Müşteri'),
('SMART-2', 'Müşteri'),
('ATEŞOĞULLARI', 'Müşteri'),
('ADİN OTEL', 'Müşteri'),
('KONYAALTI AKDENİZ', 'Müşteri'),
('YİĞİTOĞLU', 'Müşteri'),
('OVACIK', 'Müşteri'),
('ORGANİK', 'Müşteri'),
('EFSANE', 'Müşteri'),
('ÇAKRA', 'Müşteri'),
('HİDAYET', 'Müşteri'),
('DENGE', 'Müşteri'),
('AYAZ', 'Müşteri'),
('TUT', 'Müşteri'),
('AYTUĞ', 'Müşteri'),
('EMİN ÖLMEZ', 'Müşteri'),
('ADRASAN AVM', 'Müşteri'),
('BUDAK', 'Müşteri'),
('PROMİL 46', 'Müşteri'),
('REZZA', 'Müşteri'),
('BADEM', 'Müşteri'),
('DUCALE', 'Müşteri'),
('SİNEM ÖZGE HAVUZ', 'Müşteri'),
('ENES', 'Müşteri'),
('ZAFER', 'Müşteri'),
('MEHMET', 'Müşteri'),
('ÇETİNER', 'Müşteri'),
('ZUZU', 'Müşteri'),
('ÇINAR ZÜCCACİYE', 'Tedarikçi'),
('ZEYNEP', 'Müşteri'),
('AKÇİÇEK', 'Müşteri'),
('GÜL MARKET', 'Müşteri'),
('ŞORTÇU', 'Tedarikçi'),
('MİGROS', 'Müşteri'),
('ÇLK', 'Tedarikçi'),
('İZZET', 'Müşteri'),
('GÜNEŞ HEDİYELİK', 'Müşteri'),
('MARGAZ', 'Müşteri'),
('DOLU', 'Tedarikçi'),
('ANT-ANAOKULU', 'Müşteri')
) AS v(cari_kodu, yeni_tip)
WHERE c.cari_kodu = v.cari_kodu;